// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantReviewer.Models;

namespace RestaurantReviewer.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    partial class RestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("RestaurantReviewer.Models.RestaurantItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AtmposphereRating");

                    b.Property<double>("FoodRating");

                    b.Property<string>("ImgSource");

                    b.Property<string>("Name");

                    b.Property<double>("ServiceRating");

                    b.Property<double>("TotalRating");

                    b.Property<double>("ValueRating");

                    b.HasKey("Id");

                    b.ToTable("RestaurantItems");
                });

            modelBuilder.Entity("RestaurantReviewer.Models.ReviewItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AtmosphereRating");

                    b.Property<string>("Description");

                    b.Property<int>("FoodRating");

                    b.Property<long>("RestaurantId");

                    b.Property<int>("ServiceRating");

                    b.Property<string>("Title");

                    b.Property<int>("ValueRating");

                    b.HasKey("Id");

                    b.ToTable("ReviewItems");
                });
#pragma warning restore 612, 618
        }
    }
}
